提供释放的方法
dotnet-campus/AsyncWorkerCollection pull request #18
Opened 2020-09-13 07:58 UTC by lindexi

Fixes https://github.com/dotnet-campus/AsyncWorkerCollection/issues/16

2020-09-15 03:49 UTC, walterlv requested changes

2020-09-15 03:49 UTC, walterlv commented on AsyncWorkerCollection/AsyncAutoResetEvent.cs
> +        private bool _isDisposing;
```suggestion
        private bool _isDisposed;
```

_isDisposing 另有其意

2020-09-15 03:49 UTC, walterlv commented on AsyncWorkerCollection/AsyncAutoResetEvent.cs
> +        public Task<bool> WaitOneAsync()
既然这里有一个返回值，建议在文档中补充如何使用这个返回值：
1. 可以忽略？
2. 通过 while 循环等待和获取返回值，当最后一次拿值时使用值？
3. 通过 while 循环等待和获取返回值，当最后一次拿值时忽略值，并用某种方法阻止后续代码执行？

2020-09-15 03:49 UTC, walterlv commented on AsyncWorkerCollection/AsyncAutoResetEvent.cs
>                  if (_waitQueue.Any())
_waitQueue.Count > 0

2020-09-15 10:48 UTC, lindexi commented on AsyncWorkerCollection/AsyncAutoResetEvent.cs
> +        public Task<bool> WaitOneAsync()
@walterlv 看业务，加了注释

2020-09-16 00:39 UTC, walterlv approved these changes

2020-09-16 00:39 UTC, merged