添加等待初始化完成才执行的双缓存
dotnet-campus/AsyncWorkerCollection pull request #29
Opened 2020-09-26 11:14 UTC by lindexi

2020-10-10 08:24 UTC, lindexi commented
@walterlv 这个类是为了在 dotnetCampuls.Logging 这个库使用的

2020-10-10 08:24 UTC, lindexi commented
在开始的时候，立刻可以写入日志，写入的时候不卡。只有在初始完成之后，才会实际将日志写入文件或上传

2020-10-11 03:07 UTC, walterlv requested changes

2020-10-11 03:07 UTC, walterlv commented on AsyncWorkerCollection/DoubleBuffer_/DoubleBufferTaskDoUtilInitialized.cs
> +    class DoubleBufferTaskDoUtilInitialized<T>
错别字，Util = 小工具，Until = 直到

2020-10-11 03:07 UTC, walterlv commented on AsyncWorkerCollection/DoubleBuffer_/DoubleBufferTaskDoUtilInitialized.cs
> +    class DoubleBufferTaskDoUtilInitialized<T>
名字是个方法名（动词），希望改成类名（名词）。

2020-10-11 03:07 UTC, walterlv commented on AsyncWorkerCollection/DoubleBuffer_/DoubleBufferTaskDoUtilInitialized.cs
> +        private readonly Func<List<T>, Task> _doTask;
_runTask
_startTask

2020-10-11 03:10 UTC, lindexi commented on AsyncWorkerCollection/DoubleBuffer_/DoubleBufferTaskDoUtilInitialized.cs
> +    class DoubleBufferTaskDoUtilInitialized<T>
@walterlv 有建议？

2020-10-11 03:11 UTC, walterlv commented on AsyncWorkerCollection/DoubleBuffer_/DoubleBufferTaskDoUtilInitialized.cs
> +    class DoubleBufferTaskDoUtilInitialized<T>
DoubleBufferLazyInitTask

2020-10-11 04:25 UTC, walterlv approved these changes

2020-10-11 04:25 UTC, merged